services:
  db:
    image: mysql:8.0
    container_name: oremining_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: spigot_server
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
volumes:
  db_data:

